// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kuksa/val/v1/types.proto
// Original file comments:
// *******************************************************************************
// Copyright (c) 2022 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache License 2.0 which is available at
// http://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0
// ******************************************************************************
//
#ifndef GRPC_kuksa_2fval_2fv1_2ftypes_2eproto__INCLUDED
#define GRPC_kuksa_2fval_2fv1_2ftypes_2eproto__INCLUDED

#include "kuksa/val/v1/types.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace kuksa {
namespace val {
namespace v1 {

}  // namespace v1
}  // namespace val
}  // namespace kuksa


#endif  // GRPC_kuksa_2fval_2fv1_2ftypes_2eproto__INCLUDED
