// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kuksa/val/v1/val.proto
// Original file comments:
// *******************************************************************************
// Copyright (c) 2022 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache License 2.0 which is available at
// http://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0
// ******************************************************************************
//
#ifndef GRPC_kuksa_2fval_2fv1_2fval_2eproto__INCLUDED
#define GRPC_kuksa_2fval_2fv1_2fval_2eproto__INCLUDED

#include "kuksa/val/v1/val.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace kuksa {
namespace val {
namespace v1 {

// Note on authorization:
// Tokens (auth-token or auth-uuid) are sent as (GRPC / http2) metadata.
//
// The auth-token is a JWT compliant token as the examples found here:
// https://github.com/eclipse-kuksa/kuksa-databroker/tree/main/certificates/jwt
//
// See also https://github.com/eclipse-kuksa/kuksa-databroker/blob/main/doc/authorization.md#jwt-access-token
//
// Upon reception of auth-token, server shall generate an auth-uuid in metadata
// that the client can use instead of auth-token in subsequent calls.
//
class VAL final {
 public:
  static constexpr char const* service_full_name() {
    return "kuksa.val.v1.VAL";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Get entries
    virtual ::grpc::Status Get(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest& request, ::kuksa::val::v1::GetResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::GetResponse>> AsyncGet(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::GetResponse>>(AsyncGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::GetResponse>> PrepareAsyncGet(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::GetResponse>>(PrepareAsyncGetRaw(context, request, cq));
    }
    // Set entries
    virtual ::grpc::Status Set(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest& request, ::kuksa::val::v1::SetResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::SetResponse>> AsyncSet(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::SetResponse>>(AsyncSetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::SetResponse>> PrepareAsyncSet(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::SetResponse>>(PrepareAsyncSetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>> StreamedUpdate(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>>(StreamedUpdateRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>> AsyncStreamedUpdate(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>>(AsyncStreamedUpdateRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>> PrepareAsyncStreamedUpdate(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>>(PrepareAsyncStreamedUpdateRaw(context, cq));
    }
    // Subscribe to a set of entries
    //
    // Returns a stream of notifications.
    //
    // InvalidArgument is returned if the request is malformed.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::kuksa::val::v1::SubscribeResponse>> Subscribe(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::kuksa::val::v1::SubscribeResponse>>(SubscribeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::kuksa::val::v1::SubscribeResponse>> AsyncSubscribe(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::kuksa::val::v1::SubscribeResponse>>(AsyncSubscribeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::kuksa::val::v1::SubscribeResponse>> PrepareAsyncSubscribe(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::kuksa::val::v1::SubscribeResponse>>(PrepareAsyncSubscribeRaw(context, request, cq));
    }
    // Shall return information that allows the client to determine
    // what server/server implementation/version it is talking to
    // eg. kuksa-databroker 0.5.1
    virtual ::grpc::Status GetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest& request, ::kuksa::val::v1::GetServerInfoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::GetServerInfoResponse>> AsyncGetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::GetServerInfoResponse>>(AsyncGetServerInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::GetServerInfoResponse>> PrepareAsyncGetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::GetServerInfoResponse>>(PrepareAsyncGetServerInfoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Get entries
      virtual void Get(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest* request, ::kuksa::val::v1::GetResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Get(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest* request, ::kuksa::val::v1::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Set entries
      virtual void Set(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest* request, ::kuksa::val::v1::SetResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Set(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest* request, ::kuksa::val::v1::SetResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void StreamedUpdate(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::kuksa::val::v1::StreamedUpdateRequest,::kuksa::val::v1::StreamedUpdateResponse>* reactor) = 0;
      // Subscribe to a set of entries
      //
      // Returns a stream of notifications.
      //
      // InvalidArgument is returned if the request is malformed.
      virtual void Subscribe(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest* request, ::grpc::ClientReadReactor< ::kuksa::val::v1::SubscribeResponse>* reactor) = 0;
      // Shall return information that allows the client to determine
      // what server/server implementation/version it is talking to
      // eg. kuksa-databroker 0.5.1
      virtual void GetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest* request, ::kuksa::val::v1::GetServerInfoResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest* request, ::kuksa::val::v1::GetServerInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::GetResponse>* AsyncGetRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::GetResponse>* PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::SetResponse>* AsyncSetRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::SetResponse>* PrepareAsyncSetRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>* StreamedUpdateRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>* AsyncStreamedUpdateRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>* PrepareAsyncStreamedUpdateRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::kuksa::val::v1::SubscribeResponse>* SubscribeRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::kuksa::val::v1::SubscribeResponse>* AsyncSubscribeRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::kuksa::val::v1::SubscribeResponse>* PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::GetServerInfoResponse>* AsyncGetServerInfoRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kuksa::val::v1::GetServerInfoResponse>* PrepareAsyncGetServerInfoRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Get(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest& request, ::kuksa::val::v1::GetResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetResponse>> AsyncGet(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetResponse>>(AsyncGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetResponse>> PrepareAsyncGet(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetResponse>>(PrepareAsyncGetRaw(context, request, cq));
    }
    ::grpc::Status Set(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest& request, ::kuksa::val::v1::SetResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::SetResponse>> AsyncSet(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::SetResponse>>(AsyncSetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::SetResponse>> PrepareAsyncSet(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::SetResponse>>(PrepareAsyncSetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>> StreamedUpdate(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>>(StreamedUpdateRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>> AsyncStreamedUpdate(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>>(AsyncStreamedUpdateRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>> PrepareAsyncStreamedUpdate(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>>(PrepareAsyncStreamedUpdateRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::kuksa::val::v1::SubscribeResponse>> Subscribe(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::kuksa::val::v1::SubscribeResponse>>(SubscribeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::kuksa::val::v1::SubscribeResponse>> AsyncSubscribe(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::kuksa::val::v1::SubscribeResponse>>(AsyncSubscribeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::kuksa::val::v1::SubscribeResponse>> PrepareAsyncSubscribe(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::kuksa::val::v1::SubscribeResponse>>(PrepareAsyncSubscribeRaw(context, request, cq));
    }
    ::grpc::Status GetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest& request, ::kuksa::val::v1::GetServerInfoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetServerInfoResponse>> AsyncGetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetServerInfoResponse>>(AsyncGetServerInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetServerInfoResponse>> PrepareAsyncGetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetServerInfoResponse>>(PrepareAsyncGetServerInfoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Get(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest* request, ::kuksa::val::v1::GetResponse* response, std::function<void(::grpc::Status)>) override;
      void Get(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest* request, ::kuksa::val::v1::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Set(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest* request, ::kuksa::val::v1::SetResponse* response, std::function<void(::grpc::Status)>) override;
      void Set(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest* request, ::kuksa::val::v1::SetResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamedUpdate(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::kuksa::val::v1::StreamedUpdateRequest,::kuksa::val::v1::StreamedUpdateResponse>* reactor) override;
      void Subscribe(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest* request, ::grpc::ClientReadReactor< ::kuksa::val::v1::SubscribeResponse>* reactor) override;
      void GetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest* request, ::kuksa::val::v1::GetServerInfoResponse* response, std::function<void(::grpc::Status)>) override;
      void GetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest* request, ::kuksa::val::v1::GetServerInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetResponse>* AsyncGetRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetResponse>* PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::SetResponse>* AsyncSetRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::SetResponse>* PrepareAsyncSetRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>* StreamedUpdateRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>* AsyncStreamedUpdateRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>* PrepareAsyncStreamedUpdateRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::kuksa::val::v1::SubscribeResponse>* SubscribeRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest& request) override;
    ::grpc::ClientAsyncReader< ::kuksa::val::v1::SubscribeResponse>* AsyncSubscribeRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::kuksa::val::v1::SubscribeResponse>* PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetServerInfoResponse>* AsyncGetServerInfoRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetServerInfoResponse>* PrepareAsyncGetServerInfoRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Get_;
    const ::grpc::internal::RpcMethod rpcmethod_Set_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamedUpdate_;
    const ::grpc::internal::RpcMethod rpcmethod_Subscribe_;
    const ::grpc::internal::RpcMethod rpcmethod_GetServerInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Get entries
    virtual ::grpc::Status Get(::grpc::ServerContext* context, const ::kuksa::val::v1::GetRequest* request, ::kuksa::val::v1::GetResponse* response);
    // Set entries
    virtual ::grpc::Status Set(::grpc::ServerContext* context, const ::kuksa::val::v1::SetRequest* request, ::kuksa::val::v1::SetResponse* response);
    virtual ::grpc::Status StreamedUpdate(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::kuksa::val::v1::StreamedUpdateResponse, ::kuksa::val::v1::StreamedUpdateRequest>* stream);
    // Subscribe to a set of entries
    //
    // Returns a stream of notifications.
    //
    // InvalidArgument is returned if the request is malformed.
    virtual ::grpc::Status Subscribe(::grpc::ServerContext* context, const ::kuksa::val::v1::SubscribeRequest* request, ::grpc::ServerWriter< ::kuksa::val::v1::SubscribeResponse>* writer);
    // Shall return information that allows the client to determine
    // what server/server implementation/version it is talking to
    // eg. kuksa-databroker 0.5.1
    virtual ::grpc::Status GetServerInfo(::grpc::ServerContext* context, const ::kuksa::val::v1::GetServerInfoRequest* request, ::kuksa::val::v1::GetServerInfoResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Get() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::GetRequest* /*request*/, ::kuksa::val::v1::GetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGet(::grpc::ServerContext* context, ::kuksa::val::v1::GetRequest* request, ::grpc::ServerAsyncResponseWriter< ::kuksa::val::v1::GetResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Set : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Set() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Set() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Set(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::SetRequest* /*request*/, ::kuksa::val::v1::SetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSet(::grpc::ServerContext* context, ::kuksa::val::v1::SetRequest* request, ::grpc::ServerAsyncResponseWriter< ::kuksa::val::v1::SetResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamedUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamedUpdate() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_StreamedUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamedUpdate(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::kuksa::val::v1::StreamedUpdateResponse, ::kuksa::val::v1::StreamedUpdateRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamedUpdate(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::kuksa::val::v1::StreamedUpdateResponse, ::kuksa::val::v1::StreamedUpdateRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Subscribe() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::kuksa::val::v1::SubscribeResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubscribe(::grpc::ServerContext* context, ::kuksa::val::v1::SubscribeRequest* request, ::grpc::ServerAsyncWriter< ::kuksa::val::v1::SubscribeResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(3, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetServerInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetServerInfo() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_GetServerInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerInfo(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::GetServerInfoRequest* /*request*/, ::kuksa::val::v1::GetServerInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetServerInfo(::grpc::ServerContext* context, ::kuksa::val::v1::GetServerInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::kuksa::val::v1::GetServerInfoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Get<WithAsyncMethod_Set<WithAsyncMethod_StreamedUpdate<WithAsyncMethod_Subscribe<WithAsyncMethod_GetServerInfo<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Get() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::kuksa::val::v1::GetRequest, ::kuksa::val::v1::GetResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::kuksa::val::v1::GetRequest* request, ::kuksa::val::v1::GetResponse* response) { return this->Get(context, request, response); }));}
    void SetMessageAllocatorFor_Get(
        ::grpc::MessageAllocator< ::kuksa::val::v1::GetRequest, ::kuksa::val::v1::GetResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::kuksa::val::v1::GetRequest, ::kuksa::val::v1::GetResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::GetRequest* /*request*/, ::kuksa::val::v1::GetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Get(
      ::grpc::CallbackServerContext* /*context*/, const ::kuksa::val::v1::GetRequest* /*request*/, ::kuksa::val::v1::GetResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Set : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Set() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::kuksa::val::v1::SetRequest, ::kuksa::val::v1::SetResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::kuksa::val::v1::SetRequest* request, ::kuksa::val::v1::SetResponse* response) { return this->Set(context, request, response); }));}
    void SetMessageAllocatorFor_Set(
        ::grpc::MessageAllocator< ::kuksa::val::v1::SetRequest, ::kuksa::val::v1::SetResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::kuksa::val::v1::SetRequest, ::kuksa::val::v1::SetResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Set() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Set(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::SetRequest* /*request*/, ::kuksa::val::v1::SetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Set(
      ::grpc::CallbackServerContext* /*context*/, const ::kuksa::val::v1::SetRequest* /*request*/, ::kuksa::val::v1::SetResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamedUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamedUpdate() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamedUpdate(context); }));
    }
    ~WithCallbackMethod_StreamedUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamedUpdate(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::kuksa::val::v1::StreamedUpdateResponse, ::kuksa::val::v1::StreamedUpdateRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>* StreamedUpdate(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Subscribe() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackServerStreamingHandler< ::kuksa::val::v1::SubscribeRequest, ::kuksa::val::v1::SubscribeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::kuksa::val::v1::SubscribeRequest* request) { return this->Subscribe(context, request); }));
    }
    ~WithCallbackMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::kuksa::val::v1::SubscribeResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::kuksa::val::v1::SubscribeResponse>* Subscribe(
      ::grpc::CallbackServerContext* /*context*/, const ::kuksa::val::v1::SubscribeRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetServerInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetServerInfo() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::kuksa::val::v1::GetServerInfoRequest, ::kuksa::val::v1::GetServerInfoResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::kuksa::val::v1::GetServerInfoRequest* request, ::kuksa::val::v1::GetServerInfoResponse* response) { return this->GetServerInfo(context, request, response); }));}
    void SetMessageAllocatorFor_GetServerInfo(
        ::grpc::MessageAllocator< ::kuksa::val::v1::GetServerInfoRequest, ::kuksa::val::v1::GetServerInfoResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::kuksa::val::v1::GetServerInfoRequest, ::kuksa::val::v1::GetServerInfoResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetServerInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerInfo(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::GetServerInfoRequest* /*request*/, ::kuksa::val::v1::GetServerInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetServerInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::kuksa::val::v1::GetServerInfoRequest* /*request*/, ::kuksa::val::v1::GetServerInfoResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Get<WithCallbackMethod_Set<WithCallbackMethod_StreamedUpdate<WithCallbackMethod_Subscribe<WithCallbackMethod_GetServerInfo<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Get() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::GetRequest* /*request*/, ::kuksa::val::v1::GetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Set : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Set() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Set() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Set(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::SetRequest* /*request*/, ::kuksa::val::v1::SetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamedUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamedUpdate() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_StreamedUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamedUpdate(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::kuksa::val::v1::StreamedUpdateResponse, ::kuksa::val::v1::StreamedUpdateRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Subscribe() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::kuksa::val::v1::SubscribeResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetServerInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetServerInfo() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_GetServerInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerInfo(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::GetServerInfoRequest* /*request*/, ::kuksa::val::v1::GetServerInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Get() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::GetRequest* /*request*/, ::kuksa::val::v1::GetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Set : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Set() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Set() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Set(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::SetRequest* /*request*/, ::kuksa::val::v1::SetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamedUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamedUpdate() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_StreamedUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamedUpdate(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::kuksa::val::v1::StreamedUpdateResponse, ::kuksa::val::v1::StreamedUpdateRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamedUpdate(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Subscribe() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::kuksa::val::v1::SubscribeResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubscribe(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(3, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetServerInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetServerInfo() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_GetServerInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerInfo(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::GetServerInfoRequest* /*request*/, ::kuksa::val::v1::GetServerInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetServerInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Get() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Get(context, request, response); }));
    }
    ~WithRawCallbackMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::GetRequest* /*request*/, ::kuksa::val::v1::GetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Get(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Set : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Set() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Set(context, request, response); }));
    }
    ~WithRawCallbackMethod_Set() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Set(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::SetRequest* /*request*/, ::kuksa::val::v1::SetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Set(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamedUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamedUpdate() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamedUpdate(context); }));
    }
    ~WithRawCallbackMethod_StreamedUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamedUpdate(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::kuksa::val::v1::StreamedUpdateResponse, ::kuksa::val::v1::StreamedUpdateRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamedUpdate(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Subscribe() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->Subscribe(context, request); }));
    }
    ~WithRawCallbackMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::kuksa::val::v1::SubscribeResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* Subscribe(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetServerInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetServerInfo() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetServerInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetServerInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerInfo(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::GetServerInfoRequest* /*request*/, ::kuksa::val::v1::GetServerInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetServerInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Get() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::kuksa::val::v1::GetRequest, ::kuksa::val::v1::GetResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::kuksa::val::v1::GetRequest, ::kuksa::val::v1::GetResponse>* streamer) {
                       return this->StreamedGet(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::GetRequest* /*request*/, ::kuksa::val::v1::GetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::kuksa::val::v1::GetRequest,::kuksa::val::v1::GetResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Set : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Set() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::kuksa::val::v1::SetRequest, ::kuksa::val::v1::SetResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::kuksa::val::v1::SetRequest, ::kuksa::val::v1::SetResponse>* streamer) {
                       return this->StreamedSet(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Set() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Set(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::SetRequest* /*request*/, ::kuksa::val::v1::SetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::kuksa::val::v1::SetRequest,::kuksa::val::v1::SetResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetServerInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetServerInfo() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::kuksa::val::v1::GetServerInfoRequest, ::kuksa::val::v1::GetServerInfoResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::kuksa::val::v1::GetServerInfoRequest, ::kuksa::val::v1::GetServerInfoResponse>* streamer) {
                       return this->StreamedGetServerInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetServerInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetServerInfo(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::GetServerInfoRequest* /*request*/, ::kuksa::val::v1::GetServerInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetServerInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::kuksa::val::v1::GetServerInfoRequest,::kuksa::val::v1::GetServerInfoResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Get<WithStreamedUnaryMethod_Set<WithStreamedUnaryMethod_GetServerInfo<Service > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_Subscribe() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::kuksa::val::v1::SubscribeRequest, ::kuksa::val::v1::SubscribeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::kuksa::val::v1::SubscribeRequest, ::kuksa::val::v1::SubscribeResponse>* streamer) {
                       return this->StreamedSubscribe(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::kuksa::val::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::kuksa::val::v1::SubscribeResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedSubscribe(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::kuksa::val::v1::SubscribeRequest,::kuksa::val::v1::SubscribeResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_Subscribe<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_Get<WithStreamedUnaryMethod_Set<WithSplitStreamingMethod_Subscribe<WithStreamedUnaryMethod_GetServerInfo<Service > > > > StreamedService;
};

}  // namespace v1
}  // namespace val
}  // namespace kuksa


#endif  // GRPC_kuksa_2fval_2fv1_2fval_2eproto__INCLUDED
