// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kuksa/val/v1/val.proto

#include "kuksa/val/v1/val.pb.h"
#include "kuksa/val/v1/val.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace kuksa {
namespace val {
namespace v1 {

static const char* VAL_method_names[] = {
  "/kuksa.val.v1.VAL/Get",
  "/kuksa.val.v1.VAL/Set",
  "/kuksa.val.v1.VAL/StreamedUpdate",
  "/kuksa.val.v1.VAL/Subscribe",
  "/kuksa.val.v1.VAL/GetServerInfo",
};

std::unique_ptr< VAL::Stub> VAL::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VAL::Stub> stub(new VAL::Stub(channel, options));
  return stub;
}

VAL::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Get_(VAL_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Set_(VAL_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamedUpdate_(VAL_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_Subscribe_(VAL_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_GetServerInfo_(VAL_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VAL::Stub::Get(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest& request, ::kuksa::val::v1::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kuksa::val::v1::GetRequest, ::kuksa::val::v1::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void VAL::Stub::async::Get(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest* request, ::kuksa::val::v1::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kuksa::val::v1::GetRequest, ::kuksa::val::v1::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void VAL::Stub::async::Get(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest* request, ::kuksa::val::v1::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetResponse>* VAL::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kuksa::val::v1::GetResponse, ::kuksa::val::v1::GetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetResponse>* VAL::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::GetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VAL::Stub::Set(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest& request, ::kuksa::val::v1::SetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kuksa::val::v1::SetRequest, ::kuksa::val::v1::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Set_, context, request, response);
}

void VAL::Stub::async::Set(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest* request, ::kuksa::val::v1::SetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kuksa::val::v1::SetRequest, ::kuksa::val::v1::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, std::move(f));
}

void VAL::Stub::async::Set(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest* request, ::kuksa::val::v1::SetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::SetResponse>* VAL::Stub::PrepareAsyncSetRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kuksa::val::v1::SetResponse, ::kuksa::val::v1::SetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Set_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::SetResponse>* VAL::Stub::AsyncSetRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::SetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>* VAL::Stub::StreamedUpdateRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>::Create(channel_.get(), rpcmethod_StreamedUpdate_, context);
}

void VAL::Stub::async::StreamedUpdate(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::kuksa::val::v1::StreamedUpdateRequest,::kuksa::val::v1::StreamedUpdateResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::kuksa::val::v1::StreamedUpdateRequest,::kuksa::val::v1::StreamedUpdateResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamedUpdate_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>* VAL::Stub::AsyncStreamedUpdateRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>::Create(channel_.get(), cq, rpcmethod_StreamedUpdate_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>* VAL::Stub::PrepareAsyncStreamedUpdateRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>::Create(channel_.get(), cq, rpcmethod_StreamedUpdate_, context, false, nullptr);
}

::grpc::ClientReader< ::kuksa::val::v1::SubscribeResponse>* VAL::Stub::SubscribeRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::kuksa::val::v1::SubscribeResponse>::Create(channel_.get(), rpcmethod_Subscribe_, context, request);
}

void VAL::Stub::async::Subscribe(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest* request, ::grpc::ClientReadReactor< ::kuksa::val::v1::SubscribeResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::kuksa::val::v1::SubscribeResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_Subscribe_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::kuksa::val::v1::SubscribeResponse>* VAL::Stub::AsyncSubscribeRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::kuksa::val::v1::SubscribeResponse>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::kuksa::val::v1::SubscribeResponse>* VAL::Stub::PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::kuksa::val::v1::SubscribeResponse>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, false, nullptr);
}

::grpc::Status VAL::Stub::GetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest& request, ::kuksa::val::v1::GetServerInfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kuksa::val::v1::GetServerInfoRequest, ::kuksa::val::v1::GetServerInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetServerInfo_, context, request, response);
}

void VAL::Stub::async::GetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest* request, ::kuksa::val::v1::GetServerInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kuksa::val::v1::GetServerInfoRequest, ::kuksa::val::v1::GetServerInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetServerInfo_, context, request, response, std::move(f));
}

void VAL::Stub::async::GetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest* request, ::kuksa::val::v1::GetServerInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetServerInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetServerInfoResponse>* VAL::Stub::PrepareAsyncGetServerInfoRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kuksa::val::v1::GetServerInfoResponse, ::kuksa::val::v1::GetServerInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetServerInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v1::GetServerInfoResponse>* VAL::Stub::AsyncGetServerInfoRaw(::grpc::ClientContext* context, const ::kuksa::val::v1::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetServerInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

VAL::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v1::GetRequest, ::kuksa::val::v1::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VAL::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kuksa::val::v1::GetRequest* req,
             ::kuksa::val::v1::GetResponse* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v1::SetRequest, ::kuksa::val::v1::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VAL::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kuksa::val::v1::SetRequest* req,
             ::kuksa::val::v1::SetResponse* resp) {
               return service->Set(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< VAL::Service, ::kuksa::val::v1::StreamedUpdateRequest, ::kuksa::val::v1::StreamedUpdateResponse>(
          [](VAL::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::kuksa::val::v1::StreamedUpdateResponse,
             ::kuksa::val::v1::StreamedUpdateRequest>* stream) {
               return service->StreamedUpdate(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< VAL::Service, ::kuksa::val::v1::SubscribeRequest, ::kuksa::val::v1::SubscribeResponse>(
          [](VAL::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kuksa::val::v1::SubscribeRequest* req,
             ::grpc::ServerWriter<::kuksa::val::v1::SubscribeResponse>* writer) {
               return service->Subscribe(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v1::GetServerInfoRequest, ::kuksa::val::v1::GetServerInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VAL::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kuksa::val::v1::GetServerInfoRequest* req,
             ::kuksa::val::v1::GetServerInfoResponse* resp) {
               return service->GetServerInfo(ctx, req, resp);
             }, this)));
}

VAL::Service::~Service() {
}

::grpc::Status VAL::Service::Get(::grpc::ServerContext* context, const ::kuksa::val::v1::GetRequest* request, ::kuksa::val::v1::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::Set(::grpc::ServerContext* context, const ::kuksa::val::v1::SetRequest* request, ::kuksa::val::v1::SetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::StreamedUpdate(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::kuksa::val::v1::StreamedUpdateResponse, ::kuksa::val::v1::StreamedUpdateRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::Subscribe(::grpc::ServerContext* context, const ::kuksa::val::v1::SubscribeRequest* request, ::grpc::ServerWriter< ::kuksa::val::v1::SubscribeResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::GetServerInfo(::grpc::ServerContext* context, const ::kuksa::val::v1::GetServerInfoRequest* request, ::kuksa::val::v1::GetServerInfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace kuksa
}  // namespace val
}  // namespace v1

